future: true
permalink: /:title/
url: http://pmlpml.github.io
name: bbycjhj
author: bbycjhj
qq: 616466391
email: bbycjhj@163.com

duoshuo: Tan
beian: 
cnzz: 
weibo: 
github: bbycjhj
about: "这里是 bbycjhj 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
